spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:15432}/${POSTGRES_DATABASE:test}?currentSchema=public&reWriteBatchedInserts=true&sslmode=${POSTGRES_SSL_MODE:verify-full}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  upsert:
    db-type: postgresql