spring:
  datasource:
    url: jdbc:mysql://localhost:33306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  upsert:
    db-type: mysql
    use-new-mysql-syntax: true