spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/test?currentSchema=public&reWriteBatchedInserts=true
    username: postgres
    password: pg@test
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  upsert:
    db-type: postgresql