server:
  port: 8080

spring:
  application:
    name: mybatis-plus-upsert-example-mysql

  datasource:
    url: jdbc:mysql://127.0.0.1:33306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  upsert:
    enabled: true
    db-type: mysql
    use-new-mysql-syntax: true