server:
  port: 8080

spring:
  application:
    name: mybatis-plus-upsert-dynamic-db-example

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

  upsert:
    dynamic:
      enabled: true
      use-new-mysql-syntax: true
