server:
  port: 8080

spring:
  application:
    name: mybatis-plus-upsert-dynamic-db-sb3-example

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

  upsert:
    dynamic:
      enabled: true
      datasource:
        mysql:
          db-type: mysql
          use-new-mysql-syntax: true
        postgresql:
          db-type: postgresql
